include: package:flutter_lints/flutter.yaml

linter:
  rules:
    sort_constructors_first: true
    always_use_package_imports: true
    prefer_final_fields: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    use_key_in_widget_constructors: true
    always_declare_return_types: true
    sort_child_properties_last: true
    prefer_single_quotes: true
    use_super_parameters: true
    always_put_required_named_parameters_first: true
    require_trailing_commas: true

analyzer:
  exclude:
    - lib/**.g.dart
    - lib/**.freezed.dart
    - lib/app/di/di.config.dart