name: pixabay_test_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  # Model
  freezed_annotation: 2.4.4

  # Bloc
  flutter_bloc: 8.1.1

  # Routing
  auto_route: 9.2.2  

  # Utils
  shared_preferences: 2.3.2

  # DI
  get_it: 7.7.0
  provider: 6.1.2
  injectable: 2.4.4

  # Network
  dio: 5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  injectable_generator: 2.6.2
  build_runner: 2.4.12
  freezed: 2.5.7

flutter:
  uses-material-design: true